define([
	"qunit",
	"tests_base",
	"tests_setvalue",
	"tests_paste",
	"tests_initialvalue",
	"tests_date",
	"tests_dynamic",
	"tests_formatvalidate",
	"tests_ip",
	"tests_keepStatic",
	"tests_multi",
	"tests_numeric",
	"tests_numericinput",
	"tests_optional",
	"tests_phone",
	"tests_regex",
	"tests_escape",
	"tests_attributes",
	"tests_alternations",
	"tests_jitmasking",
	"tests_jquery_inputmask",
	"tests_option",
	"tests_inputeventonly"
], function(qunit) {
	qunit.load();
	qunit.start();
});
